more work on the OCF resource tool

diff --git a/ocf_resource b/ocf_resource
--- a/ocf_resource
+++ b/ocf_resource
@@ -54,23 +54,27 @@ OCF_BIN=$OCF_ROOT/resource.d
 export OCF_ROOT
 
 # Check the resource agent for validity.  Try to auto-detect when not fully-qualified.
+agent="$1"
 shift
 if [ -z "$agent" ]; then
 	print_usage; exit 1
-elif [ "$agent" != "${agent##*/}" ]; then
+elif [ "$agent" != "${agent##*::}" ]; then
 	agent_bin="$OCF_BIN/${agent//:://}"
 	if ! [ -x "$agent_bin" ]; then
+		echo "$progname: error - no such resource agent: $agent" 1>&2
 		print_usage; exit 1;
 	fi
-elif [ -x "$OCF_BIN/heartbeat/$agent"]; then
-	agent="heartbeat/$agent"
-	agent_bin="$OCF_BIN/$agent"
+elif [ -x "$OCF_BIN/heartbeat/$agent" ]; then
+	echo "$progname: warning - guessing fully-qualified resource agent name: $agent" 1>&2
+	agent="heartbeat::$agent"
+	agent_bin="$OCF_BIN/${agent//:://}"
 else
-	agent=$(find $OCF_BIN -maxdepth 2 -mindepth 2 -name IPaddr2 -not -type d | sed -ne 's@^/usr/lib/ocf/resource.d/@@p' | head -1)
+	agent=$(find $OCF_BIN -maxdepth 2 -mindepth 2 -name IPaddr2 -not -type d | sed -ne 's@^/usr/lib/ocf/resource.d/\([^/]\+\)/@\1::@p' | head -1)
 	if [ -z "$agent" ]; then
 		print_usage; exit 1
 	fi
-	agent_bin="$OCF_BIN/$agent"
+	echo "$progname: warning - guessing fully-qualified resource agent name: $agent" 1>&2
+	agent_bin="$OCF_BIN/${agent//:://}"
 fi
 
 SHORTOPTS="hVvp:MCmsAZR"
