more work on the OCF resource tool

diff --git a/ocf_resource b/ocf_resource
--- a/ocf_resource
+++ b/ocf_resource
@@ -65,12 +65,13 @@ elif [ "$agent" != "${agent##*::}" ]; then
 		print_usage; exit 1;
 	fi
 elif [ -x "$OCF_BIN/heartbeat/$agent" ]; then
-	echo "$progname: warning - guessing fully-qualified resource agent name: $agent" 1>&2
 	agent="heartbeat::$agent"
+	echo "$progname: warning - guessing fully-qualified resource agent name: $agent" 1>&2
 	agent_bin="$OCF_BIN/${agent//:://}"
 else
 	agent=$(find $OCF_BIN -maxdepth 2 -mindepth 2 -name IPaddr2 -not -type d | sed -ne 's@^/usr/lib/ocf/resource.d/\([^/]\+\)/@\1::@p' | head -1)
 	if [ -z "$agent" ]; then
+		echo "$progname: error - no such resource agent: $agent" 1>&2
 		print_usage; exit 1
 	fi
 	echo "$progname: warning - guessing fully-qualified resource agent name: $agent" 1>&2
