convert to shell params

diff --git a/ocf_resource b/ocf_resource
--- a/ocf_resource
+++ b/ocf_resource
@@ -91,7 +91,8 @@ elif [ "$agent" = "--cib-resource" ] || [ "$agent" = "-i" ]; then
 	resource="$1"
 	shift
 	agent_args=$(cibadmin -Q -o resources | xsltproc --stringparam resource-id "$resource" $HA_TOOLS_SHARE/resource2shell.xslt -)
-	agent_bin=
+	agent_bin=$(eval echo ${agent_args##* })
+	agent_args=$(eval echo ${agent_args% *})
 elif [ "$agent" != "${agent##*::}" ]; then
 	agent_bin="$OCF_BIN/${agent//:://}"
 	[ -x "$agent_bin" ] || die "no such resource agent \`$agent'"
@@ -166,11 +167,11 @@ case $1 in
 			agent_args="$agent_args OCF_RESKEY_${2%%=*}=${2#*=} "; shift
 		fi
   	;;
-  --)
+  --|'')
     break
     ;;
   *)
-    echo "Internal Error: option processing error: $1" 1>&2
+    echo "Internal Error: option processing error: \`$1\'" 1>&2
     exit 1
     ;;
 esac
